/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in full projects and kept here so the
// scaffold can type-check before the first interactive `next dev` run.
